version: '3'

services:
  backend:
    image: moez063719/achat_backend:latest
    ports:
      - "8088:8080"
    depends_on:
      - database

  frontend:
    image: moez063719/achat_frontend:latest
    ports:
      - "80:80"

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: achat
