version: '3'
services:
  mysql-db:
    image: mysql
    container_name: docker-compose-mysql-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=achatdb
    networks:
      - my-network

  spring-boot-app:
    image: youssefcloud/springpi
    container_name: docker-compose-spring-boot
    ports:
      - "8088:8089"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/achatdb?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - my-network
  angular-app:
    image: youssefcloud/angularpi
    container_name: docker-compose-angular-app
    ports:
      - "4200:80"
    environment:
      - BACKEND_API_URL=http://192.168.100.10:8080
    networks:
      - my-network

networks:
  my-network:
