version: '3'
services:
  spring-boot-app:
    image: justelyes/spring:latest
    ports:
      - "8089:8089"
    networks:
      - project

  angular-app:
    image: justelyes/front-angular:latest
    ports:
      - "4200:80"
    networks:
      - project

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: achatdb
    networks:
      - project

networks:
  project:
