version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    networks:
      - project

  backend:
    image: justelyes/spring:latest
    depends_on:
      - db
    build: ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "1234",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    networks:
      - project
  frontend:
    image: justelyes/front-angular:latest
    build: ./crud-tuto-front
    restart: on-failure
    ports:
      - 4600:4600
    networks:
      - project

networks:
  project:
    driver: bridge

